const ErrorMessage = {
  positionAppliedFor: "Position Applied For is required",
  firstName: "FirstName is required",
  fathersName: "Father 's Name is required",
  dateOfBirth: "Date Of Birth is required",
  futureDateOfBirth: "Date of birth can not be future date",
  invalidDateOfBirth: "Invalid Date Of Birth",
  emailId: "Email Id is required",
  contactedHR: "Contacted HR is required",
  mobileNumber: "Mobile No. is required",
  mobileNumberNumeric: "Mobile Number can only contain numeric value",
  mobileNumbermaxInputSize: "Mobile Number can only be 10 digits",
  invalidEmail: "Invalid Email",
  houseNumber: "House Number is required",
  street: "Street is required",
  state: "State is required",
  city: "Town/City is required",
  pincode: "Pincode is required",
  pincodeMaxInputSize: "Pincode can only be 6 digits",
  country: "Country is required",
  permanentHouseNumber: "House Number is required",
  permanentStreet: "Street is required",
  permanentState: "State is required",
  permanentCity: "Town/City is required",
  permanentPinCode: "Pincode is required",
  permanentPincodeMaxInputSize: "Pincode can only be 6 digits",
  permanentCountry: "Country is required",
  pincodeNumeric: "Pincode can only contain numeric value",
  permanentPincodeNumeric: "Pincode can only contain numeric values",
  passingYear: "Passing Year is required",
  board_university: "Board/University is required",
  college: "School/College is required",
  percentage: "Percentage is required",
  percentageNumeric: "Percentage can only contain numeric values",
  percentageMaxValue: "Percentage can not be more than 100",
  qualificationType: "CourseType is required",
  graduationCourse: "Course is required",
  postGraduationCourse: "",
  currentCTC: "Current CTC is required",
  noticePeriod: "Notice Period is required",
  expectedCTC: "Expected CTC is required",
  CTCNumeric: "CTC can only contain numeric value",
  noticePeriodNumeric: "Notice Period can only contain numeric values",
  rowRequired: "This row is required",
  currentOrganization: "Current Organization is required",
  designation: "Designation is required",
  dateOfJoining: "Date of Joining is required",
  // maxDateOfJoining: "Date Of Joining can not be after Date of Leaving",
  password: "Password is required",
  referenceName: "Reference Name is required",
  referenceContactNumber: "Contact Number is required",
  referenceRelationship: "Work Relationship is required",
  referenceDesignation: "Designation is required",
  name: "Name is Required",
  invalidUserNameOrPassword: "Invalid Username Or Password",
  userName: "Username is required",
  unauthorized: "You are not authorized for Login",
  profile: "Profile is required",
  currentAddressSection: " Current Address Section is reqd",
  permanentAddressSection: "Permanent Address Section is reqd",
  educationalDetails: "Educational Details Section is reqd",
  professionalDetails: "Professional Details Section is reqd",
  compensationDetails: "Compensation Details Section is reqd",
  age: "Age should be more than 18 years",
  questionType: "Question Type is required",
  questionCount : "Question count has to be numeric",
  lessQuestions: "Question Count > than questions in the bank"
};

export default ErrorMessage;
